# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9499f6ff412dfd032c66edc4ca672744552677e22d04e1518f06ab218ff9e066c0c8efb85e55a5d4347716cc3d3300319b894f835e17daa7388c13d1d9a7f55d

test:
  secret_key_base: 5f3b69d270d18b44050c27c665c9009a47921d07bfb3d4e49c6eba82dbdc65f5c1eb2e1cd075d917235ef6e643fc304f2c54b9f8e213fd4e8a1abcf545a1a25f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
